---
- name: create nginx config from template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ file_name }}.conf
  notify: restart nginx

- name: create systemd config from template
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/{{ file_name }}.service
  notify: reload daemon

- name: activate nginx config
  file:
    src: /etc/nginx/sites-available/{{ file_name }}.conf
    dest: /etc/nginx/sites-enabled/{{ file_name }}.conf
    state: link
  notify: restart nginx

# TBD: config postgres