---
- name: apt
  include_tasks: apt.yml # install packages
- name: project
  include_tasks: project.yml # copy project and setup venv
- name: config
  include_tasks: config.yml # configure everything
- name: service
  include_tasks: service.yml # start services