---
- name: copy nginx template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ file_name }}.conf
  notify: restart nginx

- name: enable nginx config
  file:
    src: /etc/nginx/sites-available/{{ file_name }}.conf
    dest: /etc/nginx/sites-enabled/{{ file_name }}.conf
    state: link
  notify: restart nginx

- name: check nginx running
  service:
    name: nginx
    enabled: yes
    state: started
