---
- name: fetch git repo
  git:
    repo: "{{ hamlet.git.repo }}"
    dest: "{{ hamlet.project.dir }}"
    version: "{{ hamlet.git.branch }}"
    force: yes
  notify:
    - install requirements
    - ensure gunicorn installed
    - collect static
    - update directory permissions

- meta: flush_handlers

- name: create systemd config from template
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/{{ hamlet.daemon_name }}.service
  notify: reload daemon

- name: check gunicorn systemd service running
  service:
    name: "{{ hamlet.daemon_name }}"
    enabled: yes
    state: started
