---
- name: fetch git repo
  git:
    repo: "{{ git_repo }}"
    dest: "{{ app_dir }}"
    version: "{{ branch_name }}"
    force: yes

- name: setup virtual env
  pip:
    requirements: "{{ app_dir }}/requirements.txt"
    virtualenv: "{{ app_dir }}/venv"

- name: ensure gunicorn installed
  pip:
    name: gunicorn
    virtualenv: "{{ app_dir }}/venv"

- name: collect static
  django_manage:
    command: collectstatic
    app_path: "{{ app_dir }}"
    virtualenv: "{{ app_dir }}/venv"

- name: config directory owner
  file:
    path: "{{ app_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
