---
- name: fetch git repo
  git:
    repo: "{{ git_repo }}"
    dest: "{{ app_dir }}"
    version: "{{ branch_name }}"
    force: yes
  notify:
    - install requirements
    - collect static
    - update directory permissions

- name: ensure gunicorn installed
  pip:
    name: gunicorn
    virtualenv: "{{ app_dir }}/venv"
  notify: update directory permissions

- meta: flush_handlers

- name: create systemd config from template
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/{{ file_name }}.service
  notify: reload daemon

- name: check gunicorn systemd service running
  service:
    name: "{{ file_name }}"
    enabled: yes
    state: started
