---
- name: update cache
  apt:
    cache_valid_time: 86400 # 24 hours

- name: ensure apt packages installed
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nginx
    - postgresql
    - virtualenv
