---
- name: update cache
  apt:
    cache_valid_time: 86400 # 24 hours

- name: install apt packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nginx
    - postgresql
    - virtualenv

- name: install certbot ppa
  apt_repository:
    repo: 'ppa:certbot/certbot'
  when: letsencrypt_enabled

- name: install certbot package
  apt:
    name: python-certbot-nginx
    state: present
  when: letsencrypt_enabled